name: DataDog Synthetics Action
description: 'Run DataDog Synthetics with Configurations'
author: OpenActions
branding:
  icon: 'activity'  
  color: 'blue'
inputs:
  apiKey:
    description: 'DataDog API Key'
    required: false
    default: ''
  appKey:
    description: 'DataDog Application Key'
    required: false
    default: ''
  configPath:
    description: 'DataDog Synthetics CI config file path'
    required: false
    default: ''
  datadogSite:
    description: 'DataDog Host Site'
    required: false
    default: ''
  failOnCriticalErrors:
    description: 'Set run to fail on critical errors'
    required: false
    default: false
  failOnTimeout:
    description: 'Set run to fail on timeout'
    required: false
    default: true
  files:
    description: 'Synthetic test run config files'
    required: false
    default: ''
  publicIds:
    description: 'Synthetic test public IDs'
    required: false
    default: ''
  search: 
    description: 'Search query'
    required: false
    default: ''
  subdomain:
    description: 'Custom subdomain to access DataDog'
    required: false
    default: ''
    
runs:
  using: 'composite'
  steps:
    - name: Install DataDog CI
      run: npm i -g @datadog/datadog-ci
      shell: bash

    - name: Get Action Version
      run: |
        echo ${{ github.action_path }}
        IFS='/' read -r -a PATH <<< '${{ github.action_path }}'
        echo "${PATH[-1]}"
        if [ "${PATH[-1]}" != "" ]; then
          echo "::set-output name=REF::${PATH[-1]}"
        else
          echo "::set-output name=REF::$GITHUB_SHA"
        fi
      shell: bash
      id: action-version

    - name: Checkout Actions Repo
      uses: actions/checkout@v2
      with:
        repository: OpenActions/dd-synthetics
        path: OpenActions/dd-synthetics
        ref: ${{ steps.action-version.outputs.REF }}

    - name: Setup Config File
      run: |
        if [ "${{ inputs.configPath }}" != "" ] && [ -f "${{ inputs.configPath }}" ]; then
          echo "Config file ${{ inputs.configPath }} exists"
          mv ${{ inputs.configPath }} OpenActions/dd-synthetics/src
        elif [ "${{ inputs.configPath }}" = "" ] && [ -f "datadog-ci.json" ]; then
          echo "Config file datadog-ci.json exists"
          mv datadog-ci.json OpenActions/dd-synthetics/src
        fi
      shell: bash
      
    - name: Run DataDog Action (JS)
      uses: ./OpenActions/dd-synthetics/src
      with:
        apiKey: ${{ inputs.apiKey }}
        appKey: ${{ inputs.appKey }}
        config: ${{ inputs.configPath }}
        datadogSite: ${{ inputs.datadogSite }}
        failOnCriticalErrors: ${{ inputs.failOnCriticalErrors }}
        failOnTimeout: ${{ inputs.failOnTimeout }}
        files: ${{ inputs.files }}
        publicIds: ${{ inputs.publicIds }}
        search: ${{ inputs.search }}
        subdomain: ${{ inputs.subdomain }}

    - name: Cleanup Actions Repo
      run: rm -rf OpenActions
      shell: bash
