name: DataDog Synthetics Sub Action
description: 'Run DataDog Synthetics with Configurations'
inputs:
  apiKey:
    description: 'DataDog API Key'
    required: false
    default: ''
  appKey:
    description: 'DataDog Application Key'
    required: false
    default: ''
  configPath:
    description: 'DataDog Synthetics CI config file path'
    required: false
    default: ''
  datadogSite:
    description: 'DataDog Host Site'
    required: false
    default: ''
  failOnCriticalErrors:
    description: 'Set run to fail on critical errors'
    required: false
    default: false
  failOnTimeout:
    description: 'Set run to fail on timeout'
    required: false
    default: true
  files:
    description: 'Synthetic test run config files'
    required: false
    default: ''
  publicIds:
    description: 'Synthetic test public IDs'
    required: false
    default: ''
  search: 
    description: 'Search query'
    required: false
    default: ''
  subdomain:
    description: 'Custom subdomain to access DataDog'
    required: false
    default: ''
runs:
  using: 'node12'
  main: 'index.js'