name: Composite Action

on: 
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to run action'
        required: true
        default: 'main'

jobs:
  dd_synthetics:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Test DataDog Synthetics Action
        uses: ./
        with:
          apiKey: ${{ secrets.DD_API_KEY }}
          appKey: ${{ secrets.DD_APP_KEY }}
          search: 'tag:e2e-tests'
          branch: ${{ github.event.inputs.branch }}