name: Deploy

on: workflow_dispatch

jobs:
  dd_synthetics:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: DataDog Synthetics Action
        uses: OpenActions/dd-synthetics@eb03e98c3bc5bc33b96573af68ee078a04fcbaa9
        with:
          apiKey: ${{ secrets.DD_API_KEY }}
          appKey: ${{ secrets.DD_APP_KEY }}
          search: 'tag:e2e-tests'