name: Development

on: workflow_dispatch

jobs:
  dd_synthetics:
    runs-on: {{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps: 
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Test dd-synthetics Action
        uses: ./