name: Development

on: workflow_dispatch

jobs:
  dd_synthetics:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Test dd-synthetics Action
        uses: ./