name: Pull Request

on:
  pull-request:
    branches: main

jobs:
  test-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm ci
        working-directory: './js'

      - name: Test
        run: npm run test